# coding: utf-8

"""
    CTI Backend API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_v1_graph_ingest_post(self) -> None:
        """Test case for v1_graph_ingest_post

        Ingest nodes and relationships into Neo4j
        """
        pass

    def test_v1_graph_neighbors_node_value_get(self) -> None:
        """Test case for v1_graph_neighbors_node_value_get

        Get neighbors of a node
        """
        pass

    def test_v1_graph_paths_get(self) -> None:
        """Test case for v1_graph_paths_get

        Find shortest path between two nodes
        """
        pass

    def test_v1_graph_query_post(self) -> None:
        """Test case for v1_graph_query_post

        Execute a parameterized Cypher query
        """
        pass


if __name__ == '__main__':
    unittest.main()
