# coding: utf-8

"""
    CTI Backend API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.graph_changeset import GraphChangeset

class TestGraphChangeset(unittest.TestCase):
    """GraphChangeset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GraphChangeset:
        """Test GraphChangeset
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GraphChangeset`
        """
        model = GraphChangeset()
        if include_optional:
            return GraphChangeset(
                nodes = [
                    openapi_client.models.graph_node.GraphNode(
                        id = '', 
                        labels = [
                            ''
                            ], 
                        properties = openapi_client.models.properties.properties(), )
                    ],
                relationships = [
                    openapi_client.models.graph_relationship.GraphRelationship(
                        source_id = '', 
                        target_id = '', 
                        type = '', 
                        properties = openapi_client.models.properties.properties(), )
                    ]
            )
        else:
            return GraphChangeset(
        )
        """

    def testGraphChangeset(self):
        """Test GraphChangeset"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
