# coding: utf-8

"""
    CTI Backend API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_graph_neighbors_node_value_get200_response import V1GraphNeighborsNodeValueGet200Response

class TestV1GraphNeighborsNodeValueGet200Response(unittest.TestCase):
    """V1GraphNeighborsNodeValueGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GraphNeighborsNodeValueGet200Response:
        """Test V1GraphNeighborsNodeValueGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GraphNeighborsNodeValueGet200Response`
        """
        model = V1GraphNeighborsNodeValueGet200Response()
        if include_optional:
            return V1GraphNeighborsNodeValueGet200Response(
                neighbors = [
                    None
                    ]
            )
        else:
            return V1GraphNeighborsNodeValueGet200Response(
        )
        """

    def testV1GraphNeighborsNodeValueGet200Response(self):
        """Test V1GraphNeighborsNodeValueGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
