# coding: utf-8

"""
    CTI Backend API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.generic_query_request import GenericQueryRequest

class TestGenericQueryRequest(unittest.TestCase):
    """GenericQueryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenericQueryRequest:
        """Test GenericQueryRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenericQueryRequest`
        """
        model = GenericQueryRequest()
        if include_optional:
            return GenericQueryRequest(
                cypher = '',
                params = {
                    'key' : null
                    }
            )
        else:
            return GenericQueryRequest(
                cypher = '',
        )
        """

    def testGenericQueryRequest(self):
        """Test GenericQueryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
