# coding: utf-8

"""
    CTI Backend API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_tasks_agents_invoke_post202_response import V1TasksAgentsInvokePost202Response

class TestV1TasksAgentsInvokePost202Response(unittest.TestCase):
    """V1TasksAgentsInvokePost202Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1TasksAgentsInvokePost202Response:
        """Test V1TasksAgentsInvokePost202Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1TasksAgentsInvokePost202Response`
        """
        model = V1TasksAgentsInvokePost202Response()
        if include_optional:
            return V1TasksAgentsInvokePost202Response(
                correlation_id = ''
            )
        else:
            return V1TasksAgentsInvokePost202Response(
        )
        """

    def testV1TasksAgentsInvokePost202Response(self):
        """Test V1TasksAgentsInvokePost202Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
