# coding: utf-8

"""
    CTI Backend API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_feed_request import CreateFeedRequest

class TestCreateFeedRequest(unittest.TestCase):
    """CreateFeedRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateFeedRequest:
        """Test CreateFeedRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateFeedRequest`
        """
        model = CreateFeedRequest()
        if include_optional:
            return CreateFeedRequest(
                feed_url = ''
            )
        else:
            return CreateFeedRequest(
                feed_url = '',
        )
        """

    def testCreateFeedRequest(self):
        """Test CreateFeedRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
