# coding: utf-8

"""
    CTI Backend API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_payment_intent_response import CreatePaymentIntentResponse

class TestCreatePaymentIntentResponse(unittest.TestCase):
    """CreatePaymentIntentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePaymentIntentResponse:
        """Test CreatePaymentIntentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePaymentIntentResponse`
        """
        model = CreatePaymentIntentResponse()
        if include_optional:
            return CreatePaymentIntentResponse(
                client_secret = ''
            )
        else:
            return CreatePaymentIntentResponse(
                client_secret = '',
        )
        """

    def testCreatePaymentIntentResponse(self):
        """Test CreatePaymentIntentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
