FROM python:3.12-slim

# install your deps
WORKDIR /app
COPY pyproject.toml .
COPY poetry.lock uv.lock  ./
RUN pip install --no-cache-dir poetry \
 && poetry config virtualenvs.create false \
 && poetry install --no-root --no-interaction --no-ansi

# copy the agent code
COPY . .

# default comand: override in your k8s if you like
CMD ["python", "rss_discovery_agent.py"]
