FROM python:3.10-slim
WORKDIR /app
COPY shodan_requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY shodan_stream_agent.py ./
ENV SHODAN_API_KEY=
ENV PROMETHEUS_PORT_SHODAN=9466
ENV KAFKA_BOOTSTRAP_SERVERS=kafka:9092
CMD ["python", "shodan_stream_agent.py"] 